version: '3.7'

services:
  app:
    container_name: postage_cli
    build:
      context: .
      target: app-dev
      args:
        # To authenticate to private registry either use username / password, or Oauth key/secret / etc
        # Please add Composer Auth JSON Object
        COMPOSER_AUTH: "{}"
    restart: unless-stopped
    volumes:
      - .:/app
networks:
  default:
    name: fdc